#version: 2.1
#
#orbs:
#  codecov: codecov/codecov@3.2.2
#
#jobs:
#  test-api:
#    docker:
#      - image: cimg/python:3.10.2
#    steps:
#      - checkout
#      - run:
#          name: Install requirements
#          command: pip install -r requirements.txt
#      - run:
#          name: Run tests and collect coverage
#          command: pytest --cov faslr/tests
#      - codecov/upload
#
#workflows:
#  version: 2.1
#  build-test:
#    jobs:
#      - test-api